.\" Man page for exenv
.TH EXENV 1 "November 2025" "0.1" "User Commands"
.SH NAME
exenv \- execute a command with the environment of a specified process
.SH SYNOPSIS
.B exenv
<PID> <command> [args]
.SH DESCRIPTION
The 
.B exenv
command allows you to execute a new process with the same environment variables as a specified running process.

.TP
.B <PID>
The process ID of the existing process whose environment variables you want to use.

.TP
.B <command>
The command to execute. This can include script names or binaries.

.TP
.B [args]
Optional arguments to pass to the command.

If the specified 
.B <PID>
is not valid, or if permission is denied when trying to access the environment of the specified process, the program will output an error message and terminate.
.SH EXAMPLES
To execute a command using the environment variables from the process with PID 1234 obtaining environment variables required to run Xorg application:

.RS
.B exenv 1234 /usr/bin/xclip -o
.RE

To use SSH agent of running process you can use:

.RS
.B exenv 2345 ssh user@server
.RE

To use environment of running process and add something extra:

.RS
.B exenv 3456 env FOO=bar /usr/bin/some_command --with-args yes
.RE

.SH COPYRIGHT
Copyright \(co 2025 Tomáš Čech <sleep_walker@gnu.org>

License GPLv3+: GNU GPL version 3 or later
https://gnu.org/licenses/gpl.html

.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.


.SH SEE ALSO
bash(1), sh(1)
